default['chef_jenkins']['master']['jenkins_package_version'] = '2.164'
default['chef_jenkins']['master']['jenkins_package_name'] = 'jenkins'
default['chef_jenkins']['master']['java_package_version'] = '11.0.2.7'
default['chef_jenkins']['master']['java_package_name'] = 'java-11-openjdk'
default['chef_jenkins']['master']['unzip_package_version'] = '6.00'
default['chef_jenkins']['master']['unzip_package_name'] = 'unzip'
