default['chef_jenkins']['master']['jenkins_package_version'] = '2.164'
default['chef_jenkins']['master']['jenkins_package_name'] = 'jenkins'
default['chef_jenkins']['master']['java_package_version'] = '1.8.0.201.b09'
default['chef_jenkins']['master']['java_package_name'] = 'java-1.8.0-openjdk'
default['chef_jenkins']['master']['unzip_package_version'] = '6.00'
default['chef_jenkins']['master']['unzip_package_name'] = 'unzip'
