default['chef_jenkins']['master']['jenkins_gpgkey_url'] = 'http://pkg.jenkins.io/redhat/jenkins.io.key'
default['chef_jenkins']['master']['jenkins_gpgkey_path'] = '/etc/pki/rpm-gpg/RPM-GPG-KEY-jenkins'
default['chef_jenkins']['master']['jenkins_gpgkey_path_list'] = 'file:///etc/pki/rpm-gpg/RPM-GPG-KEY-jenkins'
default['chef_jenkins']['master']['jenkins_repo_url'] = 'http://pkg.jenkins-ci.org/redhat/jenkins.repo'
default['chef_jenkins']['master']['jenkins_repo_package_base_url'] = 'http://pkg.jenkins.io/redhat/'
default['chef_jenkins']['master']['jenkins_repo_package_name'] = 'jenkins'
default['chef_jenkins']['master']['jenkins_repo_package_desc'] = 'Jenkins'
